<style>
    #tabela-pedidos.tabela-pedidos {
        max-height: 300px;
        /* Ajuste conforme necessário */
        overflow-y: auto;
    }
</style>
<div class="modal fade" id="pedidoModal" tabindex="-1" role="dialog" aria-labelledby="pedidoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pedidoModalLabel">Lista de Pedido</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container mt-4">
                    <h2>Listagem de Pedidos</h2>

                    <!-- Tabela de Pedidos com Scroll -->
                    <table id="tabela-pedidos" class="table tabela-pedidos">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Destinatário</th>
                                <th>Data do Pedido</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->pedidos as $pedido) : ?>
                                <tr>
                                    <td><?= $pedido['id'] ?></td>
                                    <td><?= $pedido['nome'] ?></td>
                                    <td><?= $pedido['created_at'] ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>