<style>
    #tabela-pedidos.tabela-pedidos {
        max-height: 300px;
        /* Ajuste conforme necessário */
        overflow-y: auto;
    }
</style>
<div class="modal fade" id="pedidoModal" tabindex="-1" role="dialog" aria-labelledby="pedidoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pedidoModalLabel">Lista de Pedido</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container mt-4">
                    <!-- Tabela de Pedidos com Scroll -->
                    <table id="tabela-pedidos" class="table tabela-pedidos">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Destinatário</th>
                                <th>Data do Pedido</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->pedidos as $pedido) : ?>
                                <tr>
                                    <td><?= $pedido['id'] ?></td>
                                    <td><?= $pedido['nome'] ?></td>
                                    <td><?= $pedido['created_at'] ?></td>
                                    <td>
                                    <a class="btn btn-sm btn-primary" href="#" data-toggle="tooltip" title="Visualizar" onclick="visualizarPedido(<?=$pedido['id']?>)">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="btn btn-sm btn-primary" href="#" data-toggle="tooltip" title="Editar">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="#" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Remover">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(()=>{
        $('[data-toggle="tooltip"]').tooltip();
    })
</script>