<div class="modal fade" id="produtoModal" tabindex="-1" role="dialog" aria-labelledby="produtoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="produtoModalLabel">Realizar Pedido</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container mt-5">
                    <form>
                        <div class="form-group">
                            <label for="nomeCliente">Nome do Cliente</label>
                            <input type="text" class="form-control" id="nomeCliente" placeholder="Digite o nome do cliente" required>
                        </div>
                        <div class="form-group">
                            <label for="cep">CEP</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="cep" placeholder="Digite o CEP" required>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button" onclick="obterInformacoesCEP()">Preencher Endereço</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="rua">Rua</label>
                            <input type="text" class="form-control" id="rua" placeholder="Digite o nome da rua" required>
                        </div>
                        <div class="form-group">
                            <label for="bairro">Bairro</label>
                            <input type="text" class="form-control" id="bairro" placeholder="Digite o nome do bairro" required>
                        </div>
                        <div class="form-group">
                            <label for="numero">Número</label>
                            <input type="text" class="form-control" id="numero" placeholder="Digite o número" required>
                        </div>
                        <div class="form-group">
                            <label for="cidade">Cidade</label>
                            <input type="text" class="form-control" id="cidade" placeholder="Digite o nome da cidade" required>
                        </div>
                        <div class="form-group">
                            <label for="estado">Estado</label>
                            <input type="text" class="form-control" id="estado" placeholder="Digite o nome do estado" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Enviar Pedido</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>