<div class="modal fade" id="produtoModal" tabindex="-1" role="dialog" aria-labelledby="produtoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="produtoModalLabel">Realizar Pedido</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container mt-5">
                    <form method="post" action="/realizarPedido">
                        <div class="form-group">
                            <input type="hidden" name="user_id" value="<?= $_POST['user_id'] ?>">
                            <label for="nomeCliente">Nome do Cliente</label>
                            <input readonly type="text" class="form-control" value="<?= $_POST['nome_cliente'] ?>" id="nome_cliente" placeholder="Digite o nome do cliente" required>
                        </div>
                        <div class="form-group">
                            <label for="cep">CEP</label>
                            <div class="input-group">
                                <input type="text" class="form-control" name="cep" maxlength="9" id="cep" placeholder="Digite o CEP" required>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button" onclick="obterInformacoesCEP()">Preencher Endereço</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="estado">UF</label>
                            <input type="text" name="uf" class="form-control" id="uf" placeholder="Digite o nome do estado" required>
                        </div>
                        <div class="form-group">
                            <label for="cidade">Cidade</label>
                            <input type="text" name="cidade" class="form-control" id="cidade" placeholder="Digite o nome da cidade" required>
                        </div>
                        <div class="form-group">
                            <label for="rua">Rua</label>
                            <input type="text" name="rua" class="form-control" id="rua" placeholder="Digite o nome da rua" required>
                        </div>
                        <div class="form-group">
                            <label for="bairro">Bairro</label>
                            <input type="text" name="bairro" class="form-control" id="bairro" placeholder="Digite o nome do bairro" required>
                        </div>
                        <div class="form-group">
                            <label for="numero">Número</label>
                            <input type="number" name="numero" class="form-control" id="numero" placeholder="Digite o número" required>
                        </div>
                        <div class="form-group">
                            <label for="envioForma">Forma de envio:</label>
                            <select class="form-control" name="envio_id" id="envio_id" onchange="calcularValor(this.value)">
                                <option value="">Não selecionada</option>
                                <? foreach ($envios as $envio) : ?>
                                    <option value="<?= $envio['id'] ?>"><?= $envio['tipo'] ?></option>
                                <? endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">R$</span>
                                </div>
                                <input class="form-control" id="valor" type="number" step="0.01" inputmode="decilmal" readonly>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="button" id="enviar_pedido" class="btn btn-sm btn-primary" onclick="enviaPedido()"> <span class="fa fa-check"></span> Enviar Pedido</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).on('input', '#cep', function() {
        var valorAtual = $(this).val();
        var valorMascarado = mascaraCEP(valorAtual);
        $(this).val(valorMascarado);
    });
</script>