<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Cadastro</h3>
                </div>
                <div class="card-body">
                    <form id="registerForm" method="post" action="/registrar"> 
                        <div class="form-group">
                            <label for="username">Usuário</label>
                            <input type="text" class="form-control" name="nome" id="nome" placeholder="Digite seu usuário" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="Digite seu email" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Senha</label>
                            <input type="password" class="form-control" name="senha" id="senha" placeholder="Digite sua senha" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <p class="mb-0">Já tem uma conta? <a href="/" class="text-primary">Faça Login</a></p>
                </div>
            </div>
        </div>
    </div>
</div>