<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h3 class="text-center"><i class="bi bi-check-circle-fill text-success"></i> Cadastro Realizado com Sucesso</h3>
        </div>
        <div class="card-body">
          <div class="alert alert-success text-center" role="alert">
            <i class="bi bi-check-circle"></i> Seu cadastro foi concluído com sucesso. Agora você pode fazer <a href="/" class="text-primary">login</a>.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>