<style>
    body {
        background-color: #f8f9fa;
    }

    .menu-card {
        width: 18rem;
        margin: 20px;
    }

    .bg-icon {
        background-position: center;
        height: 200px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .icon {
        font-size: 3em;
        /* Ajuste o tamanho do ícone conforme necessário */
    }
</style>
</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-primary">
                        <i class="fas fa-cart-plus icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="realizarPedido()">Realizar Pedido</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-info">
                        <i class="fas fa-list icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary">Lista de Pedidos</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="painel_cadastro_produto">

        </div>
    </div>