    <link rel="stylesheet" href="css/menu_principal.css">
    <nav class="navbar navbar-expand-lg navbar-primary bg-primary">
        <a class="navbar-brand text-light" href="#"><span class="text-light fa fa-circle-o-notch"></span> SWL</a>

        <!-- Botão de hamburguer para telas pequenas -->
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span>
        </button>

        <!-- Itens do Navbar -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <!-- Adicione seus outros itens do Navbar aqui -->
                <li class="nav-item m-1">
                    <a class="class  text-light" href="/menu_principal"><span class="fa fa-home"></span> Home</a>
                </li>
                <!-- Botão de deslogar -->
                <li class="nav-item m-1">
                    <a class="text-light" href="/logout"><span class="fa fa-power-off"></span> Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="loading-container">
        <div class="loading"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-primary">
                        <i class="fas fa-cart-plus icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="realizarPedido()">Realizar Pedido</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-primary">
                        <i class="fas fa-list icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="listarPedido()">Lista de Pedidos</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-primary">
                        <i class="fas fa-truck icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="abrirMenuEnvio()">Menu Envios</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="painel_realizar_pedido">

        </div>
        <div id="painel_listar_pedido">

        </div>
        <div id="painel_visualizar_pedido">

        </div>

        <div id="painel_menu_envio"></div>
    </div>