    <link rel="stylesheet" href="css/menu_principal.css">
    <nav class="navbar navbar-expand-lg navbar-primary bg-primary">
        <a class="navbar-brand" href="#"><span class="text-light">SWL</span></a>

        <!-- Botão de hamburguer para telas pequenas -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Itens do Navbar -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <!-- Adicione seus outros itens do Navbar aqui -->
                <li class="nav-item">
                    <a class="class btn btn-light" href="/menu_principal">Home</a>
                </li>
                <!-- Botão de deslogar -->
                <li class="nav-item ml-2">
                    <a class="btn btn-light" href="/logout">Deslogar</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="loading-container">
        <div class="loading"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-primary">
                        <i class="fas fa-cart-plus icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="realizarPedido()">Realizar Pedido</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-info">
                        <i class="fas fa-list icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="listarPedido()">Lista de Pedidos</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card menu-card">
                    <div class="bg-icon bg-info">
                        <i class="fas fa-truck icon text-white"></i>
                    </div>
                    <div class="card-body text-center">
                        <a href="#" class="btn btn-primary" onclick="menuPrecos()">Menu Envios</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="painel_realizar_pedido">

        </div>
        <div id="painel_listar_pedido">

        </div>
        <div id="painel_visualizar_pedido">

        </div>
    </div>