<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

        <title>SWL - Sistema de pedidos </title>
        <script src="https://kit.fontawesome.com/21274871c9.js" crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
            <!-- Adicione os scripts do Bootstrap e do jQuery (necessário para alguns recursos do Bootstrap) -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- Adicione o script do Bootstrap Icons -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/dist/js/bootstrap-icons.js"></script>
    </head>
    <body>
        <?= $this->content() ?>
    </body>
</html>